services:
  web:
    build: .
    platform: linux/amd64
    working_dir: /code
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/code
    ports:
      - "8001:8000"